kubectl --kubeconfig kubernetes-playbooks/.kube/config get pods -A
NAMESPACE                NAME                                         READY   STATUS      RESTARTS   AGE
cri-o-metrics-exporter   cri-o-metrics-exporter-64847968cd-bm9ln      1/1     Running     0          70m
ingress-nginx            ingress-nginx-admission-create-fpjts         0/1     Completed   0          65m
ingress-nginx            ingress-nginx-admission-patch-rlgk6          0/1     Completed   0          65m
ingress-nginx            ingress-nginx-controller-5486956f45-jtk28    1/1     Running     0          65m
kube-system              calico-kube-controllers-74b8fbdb46-29rtz     1/1     Running     0          70m
kube-system              calico-node-99rh8                            1/1     Running     0          70m
kube-system              calico-node-f6fhb                            1/1     Running     0          66m
kube-system              calico-node-vwkf6                            1/1     Running     0          68m
kube-system              coredns-558bd4d5db-2bndz                     1/1     Running     0          70m
kube-system              coredns-558bd4d5db-sdzcg                     1/1     Running     0          70m
kube-system              etcd-k8s-master                              1/1     Running     0          71m
kube-system              kube-apiserver-k8s-master                    1/1     Running     0          71m
kube-system              kube-controller-manager-k8s-master           1/1     Running     0          71m
kube-system              kube-proxy-6klgx                             1/1     Running     0          68m
kube-system              kube-proxy-df8tz                             1/1     Running     0          66m
kube-system              kube-proxy-w7hz4                             1/1     Running     0          70m
kube-system              kube-scheduler-k8s-master                    1/1     Running     0          71m
kube-system              metrics-server-7f64dfcd8b-zk68d              1/1     Running     0          70m
kubernetes-dashboard     dashboard-metrics-scraper-856586f554-kgtcp   1/1     Running     0          70m
kubernetes-dashboard     kubernetes-dashboard-67484c44f6-fdtl9        1/1     Running     0          70m
